// const teams = ["Turkey", "Italy", "Wales", "Switzerland", "Denmark", "Finland", "Belgium", "Russia", "Netherlands", "Ukraine", "Austria", "North Macedonia", "England", "Croatia", "Scotland", "Czech Republic", "Spain", "Sweden", "Poland", "Slovakia", "Hungary", "Portugal", "France", "Germany"]

// function teamList() {
//     var i;
//     for (i = 0; i < teams.length; i++) {
//         return(
//             <option value={teams[i]}/>
//         )
//     }
// }

function Bracket() {
    return (
        <div className="bracket">
            <div className="ro16">
                <div className="game1">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game2">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game3">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game4">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game5">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game6">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game7">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game8">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>         
            </div>
            <div className="quarters">
                <div className="game5">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game6">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game7">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game8">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
            </div>
            <div className="semis">
                <div className="game1">
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                    <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                </div>
                <div className="game2">
                <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select> 
                </div> 
            </div>
            
            <div className="finals">
                <select id="teams">
                    <option value="1">Turkey</option>
                    <option value="2">Italy</option>
                    <option value="3">Wales</option>
                    <option value="4">Switzerland</option>
                    <option value="5">Denmark</option>
                    <option value="6">Finland</option>
                    <option value="7">Belgium</option>
                    <option value="8">Russia</option>
                    <option value="9">Netherlands</option>
                    <option value="10">Ukraine</option>
                    <option value="11">Austria</option>
                    <option value="12">North Macedonia</option>
                    <option value="13">England</option>
                    <option value="14">Croatia</option>
                    <option value="15">Scotland</option>
                    <option value="16">Czech Republic</option>
                    <option value="17">Spain</option>
                    <option value="18">Sweden</option>
                    <option value="19">Poland</option>
                    <option value="20">Slovakia</option>
                    <option value="21">Hungary</option>
                    <option value="22">Portugal</option>
                    <option value="23">France</option>
                    <option value="24">Germany</option>
                </select>
                <select id="teams">
                <option value="1">Turkey</option>
                <option value="2">Italy</option>
                <option value="3">Wales</option>
                <option value="4">Switzerland</option>
                <option value="5">Denmark</option>
                <option value="6">Finland</option>
                <option value="7">Belgium</option>
                <option value="8">Russia</option>
                <option value="9">Netherlands</option>
                <option value="10">Ukraine</option>
                <option value="11">Austria</option>
                <option value="12">North Macedonia</option>
                <option value="13">England</option>
                <option value="14">Croatia</option>
                <option value="15">Scotland</option>
                <option value="16">Czech Republic</option>
                <option value="17">Spain</option>
                <option value="18">Sweden</option>
                <option value="19">Poland</option>
                <option value="20">Slovakia</option>
                <option value="21">Hungary</option>
                <option value="22">Portugal</option>
                <option value="23">France</option>
                <option value="24">Germany</option>
            </select>
            </div>
        </div>
    );
  }

export default Bracket